@host = http://localhost:5031

###
POST {{host}}/register
Content-Type: application/json

{
  "email": "muhammedlarge@gmail.com",
  "password": "SuperSecurePassword123?"
}

###
POST {{host}}/login
Content-Type: application/json

{
  "email": "muhammedlarge@gmail.com",
  "password": "SuperSecurePassword123?"
}